namespace MovieApi.Models;

public static class MovieData
{
    public static readonly IReadOnlyList<Movie> Movies = new List<Movie>
    {
        new() { Title = "The Dark Knight",                          Genre = "Action / Thriller",    Description = "A masked vigilante fights a chaotic criminal mastermind in a corrupt city. Batman must choose between his moral code and the greater good." },
        new() { Title = "The Grand Budapest Hotel",                 Genre = "Comedy",               Description = "A legendary concierge and his lobby boy get entangled in a murder mystery across a fictional European republic. Whimsical and fast-paced with a sharp wit." },
        new() { Title = "Interstellar",                             Genre = "Sci-Fi",               Description = "A former NASA pilot travels through a wormhole to find a new home for humanity. Time bends and emotional bonds are tested across galaxies." },
        new() { Title = "The Notebook",                             Genre = "Romance",              Description = "Two young lovers from different social worlds fall apart and reunite over decades. A story of enduring love told through memory and letters." },
        new() { Title = "Get Out",                                  Genre = "Horror / Thriller",    Description = "A Black man visits his white girlfriend's family estate and discovers a terrifying secret. Social commentary wrapped in pure psychological dread." },
        new() { Title = "Spirited Away",                            Genre = "Animation / Fantasy",  Description = "A young girl gets trapped in a spirit world and must work to free herself and her parents. A magical journey about courage and identity." },
        new() { Title = "The Shawshank Redemption",                 Genre = "Drama",                Description = "A man wrongly convicted of murder befriends a fellow prisoner and plans a slow escape. A deeply human story about hope and resilience behind bars." },
        new() { Title = "Knives Out",                               Genre = "Mystery / Comedy",     Description = "A detective investigates the death of a wealthy crime novelist surrounded by scheming family members. A clever whodunit with sharp humor." },
        new() { Title = "Parasite",                                 Genre = "Thriller / Drama",     Description = "A poor family infiltrates the household of a wealthy family through deception. A dark twist-filled story about class inequality." },
        new() { Title = "La La Land",                               Genre = "Musical / Romance",    Description = "Two dreamers fall in love in Los Angeles while chasing their artistic ambitions. A bittersweet story about sacrifice and what could have been." },
        new() { Title = "Mad Max: Fury Road",                       Genre = "Action",               Description = "A lone warrior and a rebel leader race across a post-apocalyptic wasteland against a tyrant. Non-stop adrenaline with stunning practical effects." },
        new() { Title = "Her",                                      Genre = "Sci-Fi / Romance",     Description = "A lonely writer falls in love with an AI operating system in near-future Los Angeles. A quiet meditation on connection, loneliness, and what makes us human." },
        new() { Title = "Coco",                                     Genre = "Animation / Family",   Description = "A young boy accidentally enters the Land of the Dead and must find his great-great-grandfather before dawn. A vibrant celebration of family and memory." },
        new() { Title = "Hereditary",                               Genre = "Horror",               Description = "A family unravels after the death of their secretive grandmother, uncovering a dark supernatural legacy. Slow dread builds into pure terror." },
        new() { Title = "The Social Network",                       Genre = "Drama / Biopic",       Description = "The founding of Facebook told through betrayal, lawsuits, and obsession. A razor-sharp portrait of ambition and friendship destroyed by success." },
        new() { Title = "Whiplash",                                 Genre = "Drama",                Description = "An ambitious young drummer pushes himself to the edge under a brutal music teacher. Tension mounts with every rehearsal until the explosive finale." },
        new() { Title = "Jurassic Park",                            Genre = "Adventure / Sci-Fi",   Description = "A theme park built around cloned dinosaurs collapses into chaos when the animals escape. Wonder and terror in equal measure." },
        new() { Title = "Eternal Sunshine of the Spotless Mind",    Genre = "Romance / Sci-Fi",     Description = "A couple undergoes a procedure to erase each other from memory after a painful breakup. Beautifully strange and emotionally devastating." },
        new() { Title = "The Princess Bride",                       Genre = "Fantasy / Comedy",     Description = "A farmhand embarks on a swashbuckling adventure to rescue the woman he loves from a corrupt prince. Funny, romantic, and endlessly quotable." },
        new() { Title = "Arrival",                                  Genre = "Sci-Fi",               Description = "A linguist is recruited to communicate with alien spacecraft that have landed worldwide. A cerebral story where language and time intersect in unexpected ways." },
        new() { Title = "Titanic",                                  Genre = "Romance / Drama",      Description = "Two strangers from different classes fall in love aboard the ill-fated ocean liner. Epic romance against a backdrop of historical tragedy." },
        new() { Title = "A Quiet Place",                            Genre = "Horror / Thriller",    Description = "A family survives in a post-apocalyptic world inhabited by creatures that hunt by sound. Tension built entirely through silence." },
        new() { Title = "The Lion King",                            Genre = "Animation / Drama",    Description = "A young lion prince flees his kingdom after his father is murdered by his uncle. A story of guilt, identity, and reclaiming your destiny." },
        new() { Title = "Pulp Fiction",                             Genre = "Crime / Drama",        Description = "Interconnected stories of hitmen, a boxer, and a gangster's wife unfold in nonlinear fashion. Darkly funny and relentlessly cool." },
        new() { Title = "Good Will Hunting",                        Genre = "Drama",                Description = "A janitor with a genius-level intellect is discovered and must choose between opportunity and the comfort of his neighborhood. A quiet story about potential and healing." },
        new() { Title = "The Truman Show",                          Genre = "Drama / Sci-Fi",       Description = "A man slowly discovers his entire life has been a television show watched by millions. A sharp satire on surveillance, reality, and free will." },
        new() { Title = "Inside Out",                               Genre = "Animation",            Description = "The emotions inside a young girl's head struggle to help her cope after her family moves cities. A surprisingly deep exploration of sadness and growing up." },
        new() { Title = "No Country for Old Men",                   Genre = "Thriller",             Description = "A hunter finds drug money in the desert and is relentlessly pursued by a remorseless killer. Bleak, tense, and philosophically haunting." },
        new() { Title = "The Martian",                              Genre = "Sci-Fi / Comedy",      Description = "An astronaut is stranded alone on Mars and must science his way to survival. Optimistic, funny, and genuinely thrilling problem-solving." },
        new() { Title = "Marriage Story",                           Genre = "Drama / Romance",      Description = "A couple navigates a painful divorce while trying to remain good parents and people. Intimate and devastating in equal parts." },
    };
}
